version: "4"

services:
  mysql:
    image: mysql:8.3
    ports:
      - "3316:3316"
    volumes:
      - ./.services/database:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=myers
      - MYSQL_PASSWORD=root
    restart: always
  wordpress:
    image: wordpress:php8.2
    ports:
      - "8000:80"
    volumes:
      - ./.services/wordpress:/var/www/html
      - ./plugin:/var/www/html/wp-content/plugins/client-first-12-core-plugin
      - ./theme:/var/www/html/wp-content/themes/client-first-12-theme
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: myers
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wpsd_
  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - mysql
    ports:
      - "8181:80"
    environment:
      MYSQL_USERNAME: myers
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql